version: 2.1

workflows:
  version: 2
  commit:
    jobs:
      - run_unittest

commonYAMLStructure:
  - &restore_venv_cache
    restore_cache:
      key: v2-dependencies-{{ checksum "core/requirements.txt" }}
  - &save_venv_cache
    save_cache:
      paths:
        - ./venv
      key: v2-dependencies-{{ checksum "core/requirements.txt" }}
  - &create_venv_and_install_dependencies
    run:
      name: create virtualenv and install dependencies
      command: |
        python -m venv venv
        . venv/bin/activate
        pip install -r core/requirements.txt

jobs:
  run_unittest:
    docker:
      - image: circleci/python:3.8.2
    working_directory: ~/repo
    steps:
      - checkout
      - *restore_venv_cache
      - *create_venv_and_install_dependencies
      - *save_venv_cache
      - run:
          name: run unittests
          command: |
            . venv/bin/activate
            python -m core.tests all
      - store_artifacts:
          path: ./core/tests/.logs
