name: Test

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  unittests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'
          cache: 'poetry'
      - run: make setup tests
