name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'
          cache: 'poetry'
      - uses: pre-commit/action@v3.0.0
      - run: poetry install
      - run: poetry run pytest
